# Generated by Django 3.0.2 on 2020-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0004_auto_20200216_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_of_report',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Icyumweru'), (2, 'Ukwezi'), (3, 'Igihembwe'), (4, 'Amezi atandatu'), (5, 'Umwaka')]),
        ),
    ]
